import { SeedArticleSpec } from '../types/seed.type';

export const SEED_ARTICLES: SeedArticleSpec[] = [
  {
    title: 'Demystifying Blockchain: Was It Intentionally Made Confusing?',
    description:
      'For many, the concept of blockchain has seemed intimidating and shrouded in mystery. Its intricate technical aspects, complex terminology, and abstract explanations have left even the most seasoned individuals scratching their heads.',
    category: 'Technology',
    tags: ['blockchain', 'web3', 'explainer'],
    authorIndex: 0,
    daysAgo: 2,
    views: 18000,
    likeCount: 4200,
  },
  {
    title: 'The Economics Behind Unpaid Internships',
    description:
      'Corporations contend that unpaid internships serve as a stepping stone toward future employment, offering invaluable industry exposure — but the math rarely works out for the intern.',
    category: 'Business',
    tags: ['economics', 'labor', 'careers'],
    authorIndex: 1,
    daysAgo: 0,
    views: 22000,
    likeCount: 1400,
  },
  {
    title: 'Embark on a Cosmic Adventure: Discovering the Wonders of Deep Space',
    description:
      'The concept of the beyond has captivated the human imagination for centuries — taking our curiosity about what lies beyond our atmosphere and turning it into a field of active discovery.',
    category: 'Science',
    tags: ['space', 'astronomy'],
    authorIndex: 2,
    daysAgo: 1,
    views: 21000,
    likeCount: 890,
  },
  {
    title: 'Classical Musician: How to Build Your Brand on Social Media',
    description:
      'While classical musicians may be locked in a timeless tradition, embracing the possibilities of social media is anything but old-fashioned.',
    category: 'Lifestyle',
    tags: ['music', 'branding', 'creators'],
    authorIndex: 3,
    daysAgo: 3,
    views: 15400,
    likeCount: 320,
  },
  {
    title: '3 Non-Latin Script Languages I Found the Easiest to Learn',
    description:
      "I've been studying languages my whole life — currently on my 12th — and the start is generally what turns most learners away. Here are three that surprised me.",
    category: 'Lifestyle',
    tags: ['language-learning', 'travel'],
    authorIndex: 4,
    daysAgo: 4,
    views: 8700,
    likeCount: 210,
  },
  {
    title: 'From Novice to Programmer: The Journey of Learning to Code',
    description:
      'The steps of grasping the basic syntax to crafting intricate algorithms — the path from novice to programmer is rarely linear, and that is exactly the point.',
    category: 'Programming',
    tags: ['learning', 'career-change'],
    authorIndex: 5,
    daysAgo: 5,
    views: 3000,
    likeCount: 1800,
  },
  {
    title: 'Blocking to Stay in Hyperfocus and Boost Your Productivity',
    description:
      'From the initial steps of grasping the basic syntax to crafting intricate algorithms, this piece walks through a distraction-blocking system that actually holds up.',
    category: 'Productivity',
    tags: ['focus', 'deep-work'],
    authorIndex: 6,
    daysAgo: 6,
    views: 7000,
    likeCount: 640,
  },
  {
    title: 'Why the Heck Are Gen Z-ers Flocking to Retro Digital Cameras?',
    description:
      'A generation raised on smartphones is spending real money on decade-old point-and-shoots. The reasons are more interesting than nostalgia alone.',
    category: 'Lifestyle',
    tags: ['culture', 'photography'],
    authorIndex: 7,
    daysAgo: 7,
    views: 31000,
    likeCount: 1220,
  },
  {
    title: '10 Food Stylists From All Over the World Tell You How to Become One',
    description:
      'A niche, competitive, and deeply visual career — here is what a decade of professionals wish they had known before starting out.',
    category: 'Design',
    tags: ['food', 'careers', 'design'],
    authorIndex: 3,
    daysAgo: 8,
    views: 19800,
    likeCount: 402,
  },
  {
    title: 'Emotional Well-Being: Negative vs. Positive Motivation',
    description:
      'Fear-based motivation gets results fast and burns out even faster. A look at what the research actually says about sustainable drive.',
    category: 'Lifestyle',
    tags: ['wellbeing', 'psychology'],
    authorIndex: 6,
    daysAgo: 9,
    views: 33500,
    likeCount: 780,
  },
  {
    title: 'Saving Does Not Equal "Smart" Personal Finance Management',
    description:
      'A dollar saved is not always a dollar well spent avoiding. Rethinking the default advice around aggressive saving.',
    category: 'Finance',
    tags: ['personal-finance', 'saving'],
    authorIndex: 1,
    daysAgo: 10,
    views: 24200,
    likeCount: 990,
  },
  {
    title: 'What Building a Side Project for Two Years Taught Me About Scope',
    description:
      'Every feature felt necessary at the time. Two years and one shipped product later, here is what I would cut on day one.',
    category: 'Programming',
    tags: ['side-projects', 'product'],
    authorIndex: 9,
    daysAgo: 11,
    views: 22100,
    likeCount: 560,
  },
  {
    title: 'The Quiet Case for Boring Technology',
    description:
      'Choosing the exciting stack is a career decision as much as a technical one. Sometimes the boring choice is the correct one.',
    category: 'Technology',
    tags: ['engineering', 'architecture'],
    authorIndex: 9,
    daysAgo: 12,
    views: 18700,
    likeCount: 1650,
  },
  {
    title: 'How Generative Tools Changed My Design Workflow (Not How You Think)',
    description:
      'Not a hype piece and not a doom piece — an honest account of what changed and what stayed exactly the same.',
    category: 'AI',
    tags: ['ai', 'design', 'workflow'],
    authorIndex: 7,
    daysAgo: 0,
    views: 12300,
    likeCount: 340,
  },
  {
    title: 'A Beginner-Friendly Tour of Neural Networks, No Math Required',
    description:
      'You do not need calculus to build an intuition for how these systems actually work. Here is the mental model I wish I had first.',
    category: 'AI',
    tags: ['ai', 'machine-learning', 'explainer'],
    authorIndex: 2,
    daysAgo: 1,
    views: 21400,
    likeCount: 2100,
  },
  {
    title: 'Solo Travel in Your Thirties: What Actually Changes',
    description:
      'The logistics are the same as your twenties. What changes is what you are actually looking for on the road.',
    category: 'Travel',
    tags: ['solo-travel', 'lifestyle'],
    authorIndex: 4,
    daysAgo: 2,
    views: 9800,
    likeCount: 240,
  },
  {
    title: 'Designing Dashboards People Actually Look At',
    description:
      'Most internal dashboards die within a month of shipping. A practical breakdown of the handful that survive.',
    category: 'Design',
    tags: ['ux', 'dashboards', 'data'],
    authorIndex: 7,
    daysAgo: 3,
    views: 17600,
    likeCount: 410,
  },
  {
    title: 'The Founder Who Turned Down Funding Three Times',
    description:
      'A profile of a bootstrapped SaaS founder and the math behind staying independent.',
    category: 'Business',
    tags: ['startups', 'bootstrapping'],
    authorIndex: 1,
    daysAgo: 4,
    views: 26300,
    likeCount: 590,
  },
  {
    title: 'Why Your Standup Meeting Is Fifteen Minutes Too Long',
    description:
      'A field guide to the small process changes that make daily standups worth attending again.',
    category: 'Productivity',
    tags: ['teams', 'meetings', 'agile'],
    authorIndex: 6,
    daysAgo: 5,
    views: 31000,
    likeCount: 705,
  },
  {
    title: 'The Physics of Why Rockets Look Like They Do',
    description:
      'Every visible design choice on a launch vehicle traces back to a physical constraint. A walkthrough of the shape.',
    category: 'Science',
    tags: ['space', 'engineering'],
    authorIndex: 2,
    daysAgo: 6,
    views: 48900,
    likeCount: 1330,
  },
  {
    title: 'Learning an Instrument as an Adult, Without the Guilt',
    description:
      'You will never be a prodigy and that was never the point. Notes on picking up piano at 34.',
    category: 'Lifestyle',
    tags: ['music', 'hobbies'],
    authorIndex: 3,
    daysAgo: 7,
    views: 6400,
    likeCount: 150,
  },
  {
    title: 'What a Decade of Freelance Writing Taught Me About Pricing',
    description:
      'The rate you start at is rarely the rate you should be charging two years in. A breakdown of how pricing should evolve.',
    category: 'Business',
    tags: ['freelancing', 'pricing'],
    authorIndex: 8,
    daysAgo: 8,
    views: 21700,
    likeCount: 480,
  },
  {
    title: 'Static Site or Framework? A Decision Tree for 2026',
    description:
      'Not every project needs a framework, and not every framework needs to be the newest one. A practical way to decide.',
    category: 'Programming',
    tags: ['web-dev', 'architecture'],
    authorIndex: 9,
    daysAgo: 9,
    views: 19500,
    likeCount: 990,
  },
  {
    title: 'The Case for Reading Physical Books Again',
    description:
      'A screen-fatigued writer on what changed after switching back to paper for a year.',
    category: 'Lifestyle',
    tags: ['reading', 'habits'],
    authorIndex: 6,
    daysAgo: 10,
    views: 14200,
    likeCount: 330,
  },
  {
    title: 'Budget Travel Without the Burnout: A Slower Itinerary',
    description:
      'Cramming twelve cities into two weeks looks great on a map and terrible in practice. An alternative pace.',
    category: 'Travel',
    tags: ['budget-travel', 'itinerary'],
    authorIndex: 4,
    daysAgo: 11,
    views: 11900,
    likeCount: 275,
  },
  {
    title: 'What Actually Happens When You Ship a Breaking API Change',
    description:
      'A postmortem-style walkthrough of a breaking change, the fallout, and the process fix that followed.',
    category: 'Programming',
    tags: ['apis', 'engineering'],
    authorIndex: 5,
    daysAgo: 0,
    views: 14800,
    likeCount: 860,
  },
];
